### ISSUE TITLE
Problems with node >= 0.11.x

### ISSUE THREAD

**Issue by shodanuk** [dbankier/JAST#10]
I'm struggling to get JAST working with any version of Node from 0.11.x upwards, The latest version I can get the stack to work with is 0.10.37.

It looks like the problem is with the STSS dependency but before I raise an issue over there, I wanted to make sure that it isn't just me being silly.

So, has anyone got JAST to work with a version of Node higher than 0.10.37?

**Comment by dbankier** [comment]
yep - errors with node-sass on 0.12. Stick to 0.10 for the moment if you can...

**Comment by shodanuk** [comment]
Ok - that's as I thought.

For anyone else reading this, I had issues with TiShadow not reloading properly using an earlier version of Node. Upgrading to 0.10.37 seems to have fixed these issues.

**Comment by danielmahon** [comment]
`grunt-stss` has been updated to support node > 0.12. Update the package.json to the latest version to fix.
