### ISSUE TITLE
Q: Replace Babel with Typescript?

### ISSUE THREAD

**Issue by dbankier** [dbankier/JAST#18]
Being playing with Typescript and starting to like it.
Curious what people think of replacing babel with Typescript.
I could support both, compiling based on extension...
(I guess it would make the project TAST instead of JAST...)

**Comment by evoactivity** [comment]
Might be worth adding as an option, personally I prefer writing code that is actual javascript (or will be).

**Comment by dbankier** [comment]
@evoactivity that is a common argument so I'll leave it be
(that said typescript isn't another coffeescript - so far it mostly future javascript with a type system)
