### ISSUE TITLE
How do I build and test on my physcial device?

### ISSUE THREAD

**Issue by evoactivity** [dbankier/JAST#19]
The readme doesn't really mention how this would be achieved. The TIShadow docs don't really shed any light on this either and JAST takes care of the TiShadow aspects using grunt so I'm not entirely sure what's going on under the hood.

Also running `grunt dev -p ios` doesn't work but `grunt dev -p iphone` does, it might be worth reworking the readme to make sure it matches how the stack should be used and to be a bit friendlier to new users.

**Comment by dbankier** [comment]
You can modify the ti-args at the top of the Gruntfile to suit your environment.
Happy for any help with updating the README :)
